
* Overview

This repository contains the replication scripts for:

- Ferrari, D. (2024). The Effect of Combining a Populist Rhetoric into Right-Wing Positions on Candidates' Electoral Support. Electoral Studies (Conditionally Accepted), Volume 89 (https://doi.org/10.1016/j.electstud.2024.102787).


Bibtex citation:

#+BEGIN_SRC bibtex

@article{ferrari2024effect,
	author  = {Diogo Ferrari},
	title   = {The Effect of Combining a Populist Rhetoric into Right-Wing Positions on Candidates' Electoral Support},
	year    = {2024},
	journal = {Electoral Studies},
	month   = {June},
	volume  = {Volume 89},
      doi     = {https://doi.org/10.1016/j.electstud.2024.102787}
}

#+END_SRC

The files in this repository include:

1. The scripts used to replicate the analyses and create the tables and figures in the manuscript.
2. The anonymized data sets used in the analyses.

#+BEGIN_SRC ascii
.
├── data
│   └── final                        <- folder with data used in the analyses 
│                                       (only aggregated data; see privacy statement)
├── man
│   └── tables-and-figures           <- folder to save the tables and figures
├── src
│   └── model                        <- scripts to reproduce the analyses, tables, and figures
└── README.org                       <- this file
#+END_SRC

* System Requirements
** Hardware

The analyses in the manuscript were produced using:
- Intel® Core™ i7-10610U × 8
- 48 GiB RAM

** Software

Original settings used to produce the manuscript analyses:

#+BEGIN_SRC R :exports code :results none
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 23.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.11.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Los_Angeles
tzcode source: system (glibc)

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] broom_1.0.5        readxl_1.4.2       kableExtra_1.3.4   fixest_0.11.2      modelsummary_1.4.0
 [6] ggbrace_0.1.0      ggtext_0.1.2       ggpubr_0.6.0       patchwork_1.1.2    labelled_2.11.0   
[11] furrr_0.3.1        future_1.32.0      glue_1.6.2         magrittr_2.0.3     sjmisc_2.8.9      
[16] writexl_1.4.2      ggh4x_0.2.5        lubridate_1.9.2    forcats_1.0.0      stringr_1.5.1     
[21] dplyr_1.1.4        purrr_1.0.2        readr_2.1.4        tidyr_1.3.0        tibble_3.2.1      
[26] tidyverse_2.0.0    ggdark_0.2.1       gtsummary_1.7.1    ggplot2_3.4.2      RColorBrewer_1.1-3

loaded via a namespace (and not attached):
  [1] splines_4.3.1           later_1.3.1             cellranger_1.1.0        datawizard_0.9.0       
  [5] lifecycle_1.0.4         rstatix_0.7.2           rprojroot_2.0.3         globals_0.16.2         
  [9] lattice_0.21-8          vroom_1.6.5             MASS_7.3-60             insight_0.19.7         
 [13] backports_1.4.1         rmarkdown_2.21          httpuv_1.6.11           askpass_1.1            
 [17] multcomp_1.4-23         abind_1.4-5             rvest_1.0.3             TH.data_1.1-2          
 [21] sandwich_3.0-2          gdtools_0.3.3           dreamerr_1.4.0          listenv_0.9.0          
 [25] crul_1.3                performance_0.10.8      parallelly_1.35.0       svglite_2.1.1          
 [29] commonmark_1.9.0        codetools_0.2-19        DT_0.27                 xml2_1.3.4             
 [33] tidyselect_1.2.0        httpcode_0.3.0          farver_2.1.1            effectsize_0.8.6       
 [37] webshot_0.5.4           broom.helpers_1.13.0    jsonlite_1.8.4          ellipsis_0.3.2         
 [41] Formula_1.2-5           survival_3.5-5          emmeans_1.8.6           systemfonts_1.0.4      
 [45] tools_4.3.1             Rcpp_1.0.10             gridExtra_2.3           xfun_0.39              
 [49] withr_2.5.2             numDeriv_2016.8-1.1     fastmap_1.1.1           fansi_1.0.5            
 [53] openssl_2.0.6           digest_0.6.31           timechange_0.2.0        R6_2.5.1               
 [57] mime_0.12               estimability_1.4.1      textshaping_0.3.6       colorspace_2.1-0       
 [61] markdown_1.6            utf8_1.2.4              generics_0.1.3          fontLiberation_0.1.0   
 [65] data.table_1.14.8       httr_1.4.6              htmlwidgets_1.6.2       parameters_0.21.3      
 [69] pkgconfig_2.0.3         gtable_0.3.3            htmltools_0.5.5         fontBitstreamVera_0.1.1
 [73] carData_3.0-5           scales_1.2.1            knitr_1.42              rstudioapi_0.14        
 [77] tzdb_0.4.0              coda_0.19-4             checkmate_2.2.0         nlme_3.1-162           
 [81] curl_5.0.0              zoo_1.8-12              sjlabelled_1.2.0        parallel_4.3.1         
 [85] pillar_1.9.0            vctrs_0.6.5             promises_1.2.0.1        car_3.1-2              
 [89] xtable_1.8-4            evaluate_0.21           mvtnorm_1.1-3           cli_3.6.1              
 [93] compiler_4.3.1          rlang_1.1.2             crayon_1.5.2            future.apply_1.10.0    
 [97] ggsignif_0.6.4          labeling_0.4.2          stringi_1.8.2           viridisLite_0.4.2      
[101] assertthat_0.2.1        tables_0.9.17           munsell_0.5.0           bayestestR_0.13.1      
[105] fontquiver_0.2.1        Matrix_1.6-4            hms_1.1.3               bit64_4.0.5            
[109] gfonts_0.2.0            shiny_1.7.4             haven_2.5.4             gridtext_0.1.5         
[113] gt_0.9.0                huxtable_5.5.2          bit_4.0.5              


#+END_SRC                   


** Non-standard software and hardware

No non-standard software or hardware was used.

* Instructions for replication

1. Download this repository to your local computer and unzip it if necessary
2. Open the terminal
3. From the terminal window, go to the subfolder =/src/model/= within your local folder with this repository and run:

   #+BEGIN_SRC shell
R CMD BATCH --no-save model.R &
   #+END_SRC

When the script finishes, it will save a file named =model.Rout= with the R log file in the folder =/src/model/=. It will also create all tables and figures within the folder =/man/tables-and-figures/.=

